#ifndef CONFIG
#define CONFIG

#define PIN_BUTTON_TUNE_LEFT_0 9
#define PIN_BUTTON_TUNE_LEFT_1 8
#define PIN_BUTTON_TUNE_LEFT_2 7
#define PIN_BUTTON_TUNE_LEFT_3 6
#define PIN_BUTTON_TUNE_LEFT_SIDE 5
#define PIN_BUTTON_TUNE_RIGHT_SIDE 4
#define PIN_BUTTON_TUNE_RIGHT_3 3
#define PIN_BUTTON_TUNE_RIGHT_2 2
#define PIN_BUTTON_TUNE_RIGHT_1 1
#define PIN_BUTTON_TUNE_RIGHT_0 0
#define PIN_BUTTON_SUB_LEFT_0 13
#define PIN_BUTTON_SUB_LEFT_1 12
#define PIN_BUTTON_SUB_RIGHT_0 11
#define PIN_BUTTON_SUB_RIGHT_1 10

#define PIN_BUTTON_DUPLICATED_UPARROW 8
#define PIN_BUTTON_DUPLICATED_DOWNARROW 1
#define PIN_BUTTON_DUPLICATED_LEFTARROW 11
#define PIN_BUTTON_DUPLICATED_RIGHTARROW 10

#define KEYBOARD_BUTTON_TUNE_LEFT_0 'a'
#define KEYBOARD_BUTTON_TUNE_LEFT_1 's'
#define KEYBOARD_BUTTON_TUNE_LEFT_2 'd'
#define KEYBOARD_BUTTON_TUNE_LEFT_3 'c'
#define KEYBOARD_BUTTON_TUNE_LEFT_SIDE 129
#define KEYBOARD_BUTTON_TUNE_RIGHT_SIDE 133
#define KEYBOARD_BUTTON_TUNE_RIGHT_3 ','
#define KEYBOARD_BUTTON_TUNE_RIGHT_2 'l'
#define KEYBOARD_BUTTON_TUNE_RIGHT_1 ';'
#define KEYBOARD_BUTTON_TUNE_RIGHT_0 '\''
#define KEYBOARD_BUTTON_SUB_LEFT_0 179
#define KEYBOARD_BUTTON_SUB_LEFT_1 176
#define KEYBOARD_BUTTON_SUB_RIGHT_0 '1'
#define KEYBOARD_BUTTON_SUB_RIGHT_1 '2'

#define KEYBOARD_BUTTON_DUPLICATED_UPARROW 218
#define KEYBOARD_BUTTON_DUPLICATED_DOWNARROW 217
#define KEYBOARD_BUTTON_DUPLICATED_LEFTARROW 216
#define KEYBOARD_BUTTON_DUPLICATED_RIGHTARROW 215

#endif
