#ifndef DEFAULT
#define DEFAULT

#define DEFAULT_KEY_ESC 177
#define DEFAULT_KEY_ENTER 176
#define DEFAULT_KEY_TAB 179
#define DEFAULT_KEY_SPACE -1
#define DEFAULT_KEY_SPEEDUP -1  // digit1
#define DEFAULT_KEY_SPEEDDOWN -1  // digit2
#define DEFAULT_KEY_REWINDKEY 178
#define DEFAULT_KEY_LEFTSHIFT 129
#define DEFAULT_KEY_RIGHTSHIFT 134
#define DEFAULT_KEY_ARROWUP 218
#define DEFAULT_KEY_ARROWDOWN 217
#define DEFAULT_KEY_ARROWLEFT 216
#define DEFAULT_KEY_ARROWRIGHT 215
#define DEFAULT_KEY_TUNELEFTSIDE 129
#define DEFAULT_KEY_TUNES 83
#define DEFAULT_KEY_TUNED 68
#define DEFAULT_KEY_TUNEF 70
#define DEFAULT_KEY_TUNEC 67
#define DEFAULT_KEY_TUNEM 77
#define DEFAULT_KEY_TUNEJ 74
#define DEFAULT_KEY_TUNEK 75
#define DEFAULT_KEY_TUNEL 76
#define DEFAULT_KEY_TUNERIGHTSIDE 134
#define DEFAULT_KEY_EMOTICON1 -1  // digit3
#define DEFAULT_KEY_EMOTICON2 -1  // digit4
#define DEFAULT_KEY_EMOTICON3 -1  // digit5
#define DEFAULT_KEY_EMOTICON4 -1  // digit6
#define DEFAULT_KEY_EMOTICON5 -1  // digit7

#endif
