name: Test

on:
  push:
    branches:
      - main

jobs:
  test_controller:
    name: Test Controller Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Run Test
        run: |
          cd controller_test
          cmake -S . -B build
          cmake --build build
          cd make && ctest
